# Generated by Django 4.1.2 on 2022-10-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_carros_filmes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmes',
            old_name='marca',
            new_name='gênero',
        ),
        migrations.RenameField(
            model_name='filmes',
            old_name='modelo',
            new_name='nome',
        ),
    ]
